export const TYPES = {
    SEND_GRID_API_KEY: Symbol.for('SEND_GRID_API_KEY'),
    SEND_GRID_SENDER_EMAIL: Symbol.for('SEND_GRID_SENDER_EMAIL'),
    EMAIL_SERVICE: Symbol.for('EMAIL_SERVICE'),
    RECEIVER_EMAIL: Symbol.for('RECEIVER_EMAIL'),
}